/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#003527',
        'primary-container': '#064e3b',
        'on-primary': '#ffffff',
        'on-primary-container': '#80bea6',
        'primary-fixed': '#b0f0d6',
        'primary-fixed-dim': '#95d3ba',
        secondary: '#565e74',
        'secondary-container': '#dae2fd',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5c647a',
        tertiary: '#003623',
        'tertiary-container': '#004f34',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#31c98f',
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-container': '#e5eeff',
        'surface-container-low': '#eff4ff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#2b6954',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#404944',
        'on-background': '#0b1c30',
        outline: '#707974',
        'outline-variant': '#bfc9c3',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#95d3ba',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        base: '8px',
        md: '24px',
        gutter: '24px',
        lg: '40px',
        xl: '64px',
        margin: '32px',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
