const { v4: uuidv4 } = require("uuid");
const bcrypt = require("bcryptjs");

// ─── IDs ───────────────────────────────────────────────────────────────────
const defaultRestaurantId = uuidv4();
const est2Id = uuidv4();
const est3Id = uuidv4();
const est4Id = uuidv4();
const est5Id = uuidv4();

// ─── Settings factory ──────────────────────────────────────────────────────
const createDefaultSettings = (restaurantName = "My Restaurant") => ({
  restaurantName,
  address: "",
  phone: "",
  email: "",
  openingHours: {
    monday: "12:00-23:00",
    tuesday: "12:00-23:00",
    wednesday: "12:00-23:00",
    thursday: "12:00-23:00",
    friday: "12:00-00:00",
    saturday: "11:00-00:00",
    sunday: "closed",
  },
  currency: "USD",
  timezone: "America/New_York",
  notifications: {
    emailReservations: true,
    smsConfirmations: false,
    dailyReport: true,
  },
  tableCapacity: 20,
});

// ─── Manager users ─────────────────────────────────────────────────────────
const users = [
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "Alex Morgan",
    email: "manager@grandbistro.com",
    password: bcrypt.hashSync("password123", 10),
    role: "manager",
    restaurant: "The Grand Bistro",
    avatar: null,
    createdAt: new Date("2024-01-15").toISOString(),
  },
];

// ─── Client users (guests who sign up and log in) ─────────────────────────
const clientUsers = [
  {
    id: uuidv4(),
    name: "Julianne Hayes",
    email: "julianne@example.com",
    password: bcrypt.hashSync("password123", 10),
    role: "client",
    phone: "+1 555-1001",
    avatar: null,
    createdAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: uuidv4(),
    name: "Robert Kimmich",
    email: "robert@example.com",
    password: bcrypt.hashSync("password123", 10),
    role: "client",
    phone: "+1 555-1002",
    avatar: null,
    createdAt: new Date("2024-07-10").toISOString(),
  },
];

// ─── Establishments (places clients browse) ────────────────────────────────
const establishments = [
  {
    id: defaultRestaurantId,
    name: "The Grand Bistro",
    type: "restaurant",
    description:
      "An upscale French-inspired bistro offering seasonal menus, fine wines, and an intimate dining experience in the heart of the city.",
    address: "24 Rue de la Paix, Paris 75001",
    phone: "+33 1 42 96 00 00",
    email: "contact@grandbistro.com",
    rating: 4.8,
    reviewCount: 124,
    priceRange: "$$$",
    openingHours: "12:00 – 23:00",
    image: null,
    tags: ["Fine Dining", "French", "Wine Bar"],
    tableCapacity: 20,
  },
  {
    id: est2Id,
    name: "Oasis Lounge & Bar",
    type: "bar",
    description:
      "A stylish rooftop bar with craft cocktails, live DJ sets, and panoramic city views. Perfect for after-work drinks and late-night socializing.",
    address: "88 Skyline Ave, New York NY 10001",
    phone: "+1 212-555-0200",
    email: "hello@oasislounge.com",
    rating: 4.5,
    reviewCount: 89,
    priceRange: "$$",
    openingHours: "17:00 – 02:00",
    image: null,
    tags: ["Rooftop", "Cocktails", "Live Music"],
    tableCapacity: 30,
  },
  {
    id: est3Id,
    name: "Grand Legacy Hotel",
    type: "hotel",
    description:
      "A luxury 5-star hotel featuring world-class amenities, fine dining, a spa, and breathtaking skyline views. Your home away from home.",
    address: "1 Legacy Boulevard, Chicago IL 60601",
    phone: "+1 312-555-0300",
    email: "reservations@grandlegacy.com",
    rating: 4.9,
    reviewCount: 312,
    priceRange: "$$$$",
    openingHours: "24/7",
    image: null,
    tags: ["Luxury", "Spa", "Fine Dining", "Conference"],
    tableCapacity: 80,
  },
  {
    id: est4Id,
    name: "Urban Eats Kitchen",
    type: "restaurant",
    description:
      "A casual fast-casual spot celebrating street food from around the world. Bold flavors, fresh ingredients, and a buzzing atmosphere.",
    address: "55 Market Street, San Francisco CA 94105",
    phone: "+1 415-555-0400",
    email: "eat@urbaneats.com",
    rating: 4.3,
    reviewCount: 201,
    priceRange: "$",
    openingHours: "10:00 – 22:00",
    image: null,
    tags: ["Casual", "Street Food", "Vegan Options"],
    tableCapacity: 40,
  },
  {
    id: est5Id,
    name: "Zephyr Boutique Motel",
    type: "motel",
    description:
      "A charming boutique motel with themed rooms, a cozy café, and a welcoming garden patio. Great value without compromising on style.",
    address: "300 Coastal Road, Miami FL 33101",
    phone: "+1 305-555-0500",
    email: "stay@zephyrmotel.com",
    rating: 4.1,
    reviewCount: 67,
    priceRange: "$$",
    openingHours: "24/7",
    image: null,
    tags: ["Boutique", "Garden", "Café"],
    tableCapacity: 15,
  },
];

// ─── Admin clients (manager-side CRM records) ──────────────────────────────
const clients = [
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "Sophia Andersen",
    email: "sophia@email.com",
    phone: "+1 555-0101",
    visits: 12,
    totalSpent: 1840.5,
    lastVisit: "2024-11-20",
    vip: true,
    notes: "Prefers window table, allergic to shellfish",
    tags: ["VIP", "Regular"],
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "Marcus Liu",
    email: "marcus.liu@email.com",
    phone: "+1 555-0102",
    visits: 7,
    totalSpent: 920.0,
    lastVisit: "2024-11-18",
    vip: false,
    notes: "Birthday on March 14th",
    tags: ["Regular"],
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "Elena Vasquez",
    email: "elena.v@email.com",
    phone: "+1 555-0103",
    visits: 3,
    totalSpent: 310.0,
    lastVisit: "2024-11-10",
    vip: false,
    notes: "",
    tags: ["New"],
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "James Thornton",
    email: "j.thornton@corp.com",
    phone: "+1 555-0104",
    visits: 21,
    totalSpent: 4250.75,
    lastVisit: "2024-11-22",
    vip: true,
    notes: "Corporate account - expense reporting needed",
    tags: ["VIP", "Corporate"],
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "Aisha Okoye",
    email: "aisha.o@email.com",
    phone: "+1 555-0105",
    visits: 5,
    totalSpent: 680.0,
    lastVisit: "2024-11-15",
    vip: false,
    notes: "Vegan menu required",
    tags: ["Regular", "Dietary"],
  },
];

// ─── Menu items (per establishment) ───────────────────────────────────────
const menuItems = [
  // The Grand Bistro
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "Truffle Risotto",
    category: "Mains",
    price: 28.5,
    description: "Arborio rice, black truffle, parmesan, wild mushrooms",
    available: true,
    popular: true,
    image: null,
    allergens: ["dairy", "gluten"],
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "Burrata & Heirloom Tomatoes",
    category: "Starters",
    price: 16.0,
    description: "Fresh burrata, heirloom tomatoes, basil oil, fleur de sel",
    available: true,
    popular: true,
    image: null,
    allergens: ["dairy"],
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "Grilled Sea Bass",
    category: "Mains",
    price: 34.0,
    description: "Line-caught sea bass, saffron beurre blanc, fennel salad",
    available: true,
    popular: false,
    image: null,
    allergens: ["fish"],
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "Dark Chocolate Fondant",
    category: "Desserts",
    price: 12.5,
    description:
      "Warm chocolate fondant, vanilla bean ice cream, caramel sauce",
    available: true,
    popular: true,
    image: null,
    allergens: ["dairy", "gluten", "eggs"],
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "Wagyu Beef Tartare",
    category: "Starters",
    price: 22.0,
    description: "A5 wagyu, capers, egg yolk, Dijon mustard, toast points",
    available: true,
    popular: false,
    image: null,
    allergens: ["eggs", "gluten"],
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "Sommelier Wine Flight",
    category: "Beverages",
    price: 45.0,
    description: "Three curated wines paired to your meal by our sommelier",
    available: true,
    popular: false,
    image: null,
    allergens: [],
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "Lobster Bisque",
    category: "Starters",
    price: 18.0,
    description: "Classic bisque, cognac cream, chive oil, crusty bread",
    available: false,
    popular: false,
    image: null,
    allergens: ["shellfish", "dairy", "gluten"],
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    name: "Creme Brulee",
    category: "Desserts",
    price: 11.0,
    description: "Tahitian vanilla custard, torched caramel crust",
    available: true,
    popular: true,
    image: null,
    allergens: ["dairy", "eggs"],
  },

  // Oasis Lounge & Bar
  {
    id: uuidv4(),
    restaurantId: est2Id,
    name: "Signature Mojito",
    category: "Cocktails",
    price: 14.0,
    description: "Fresh mint, lime, white rum, soda, sugar cane",
    available: true,
    popular: true,
    image: null,
    allergens: [],
  },
  {
    id: uuidv4(),
    restaurantId: est2Id,
    name: "Truffle Fries",
    category: "Bites",
    price: 9.0,
    description: "Crispy fries tossed in truffle oil and parmesan",
    available: true,
    popular: true,
    image: null,
    allergens: ["dairy", "gluten"],
  },
  {
    id: uuidv4(),
    restaurantId: est2Id,
    name: "Aperol Spritz",
    category: "Cocktails",
    price: 12.0,
    description: "Aperol, prosecco, soda water, orange slice",
    available: true,
    popular: false,
    image: null,
    allergens: [],
  },
  {
    id: uuidv4(),
    restaurantId: est2Id,
    name: "Sliders Board",
    category: "Bites",
    price: 16.0,
    description: "Three mini wagyu sliders with house pickles",
    available: true,
    popular: false,
    image: null,
    allergens: ["gluten", "eggs"],
  },

  // Grand Legacy Hotel
  {
    id: uuidv4(),
    restaurantId: est3Id,
    name: "Club Sandwich",
    category: "Mains",
    price: 22.0,
    description: "Triple-decker with chicken, bacon, avocado, and aioli",
    available: true,
    popular: true,
    image: null,
    allergens: ["gluten", "eggs"],
  },
  {
    id: uuidv4(),
    restaurantId: est3Id,
    name: "Eggs Benedict",
    category: "Breakfast",
    price: 18.0,
    description: "Poached eggs, hollandaise, Canadian bacon, English muffin",
    available: true,
    popular: true,
    image: null,
    allergens: ["gluten", "dairy", "eggs"],
  },
  {
    id: uuidv4(),
    restaurantId: est3Id,
    name: "Filet Mignon",
    category: "Mains",
    price: 65.0,
    description: "8oz center-cut filet, truffle butter, potato gratin",
    available: true,
    popular: false,
    image: null,
    allergens: ["dairy"],
  },
  {
    id: uuidv4(),
    restaurantId: est3Id,
    name: "Cheese Platter",
    category: "Starters",
    price: 28.0,
    description:
      "Selection of five artisanal cheeses with honeycomb and crackers",
    available: true,
    popular: false,
    image: null,
    allergens: ["dairy", "gluten"],
  },

  // Urban Eats Kitchen
  {
    id: uuidv4(),
    restaurantId: est4Id,
    name: "Korean BBQ Bowl",
    category: "Bowls",
    price: 13.0,
    description: "Marinated beef, jasmine rice, kimchi, sesame, spring onion",
    available: true,
    popular: true,
    image: null,
    allergens: ["gluten"],
  },
  {
    id: uuidv4(),
    restaurantId: est4Id,
    name: "Falafel Wrap",
    category: "Wraps",
    price: 10.0,
    description: "Crispy falafel, hummus, tabbouleh, tahini, flatbread",
    available: true,
    popular: true,
    image: null,
    allergens: ["gluten", "sesame"],
  },
  {
    id: uuidv4(),
    restaurantId: est4Id,
    name: "Mango Lassi",
    category: "Drinks",
    price: 5.0,
    description: "Fresh mango blended with yogurt, cardamom, honey",
    available: true,
    popular: false,
    image: null,
    allergens: ["dairy"],
  },

  // Zephyr Boutique Motel
  {
    id: uuidv4(),
    restaurantId: est5Id,
    name: "Continental Breakfast",
    category: "Breakfast",
    price: 12.0,
    description: "Pastries, fruit, yogurt, juice, and coffee",
    available: true,
    popular: true,
    image: null,
    allergens: ["gluten", "dairy"],
  },
  {
    id: uuidv4(),
    restaurantId: est5Id,
    name: "Garden Salad",
    category: "Light Bites",
    price: 9.0,
    description: "Mixed greens, cherry tomatoes, cucumber, lemon vinaigrette",
    available: true,
    popular: false,
    image: null,
    allergens: [],
  },
];

// ─── Admin-side reservations ───────────────────────────────────────────────
const reservations = [
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    clientId: clients[0].id,
    clientName: "Sophia Andersen",
    date: "2024-11-25",
    time: "19:00",
    partySize: 2,
    table: "T-4",
    status: "confirmed",
    specialRequests: "Window table preferred",
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    clientId: clients[3].id,
    clientName: "James Thornton",
    date: "2024-11-25",
    time: "20:00",
    partySize: 6,
    table: "T-12",
    status: "confirmed",
    specialRequests: "Corporate dinner, need receipts",
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    clientId: clients[1].id,
    clientName: "Marcus Liu",
    date: "2024-11-26",
    time: "18:30",
    partySize: 4,
    table: "T-7",
    status: "pending",
    specialRequests: "",
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    clientId: clients[2].id,
    clientName: "Elena Vasquez",
    date: "2024-11-26",
    time: "19:30",
    partySize: 2,
    table: "T-3",
    status: "confirmed",
    specialRequests: "",
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    clientId: clients[4].id,
    clientName: "Aisha Okoye",
    date: "2024-11-27",
    time: "20:30",
    partySize: 3,
    table: "T-9",
    status: "pending",
    specialRequests: "Vegan menu required for all guests",
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    restaurantId: defaultRestaurantId,
    clientId: null,
    clientName: "Walk-in Guest",
    date: "2024-11-24",
    time: "13:00",
    partySize: 2,
    table: "T-1",
    status: "completed",
    specialRequests: "",
    createdAt: new Date().toISOString(),
  },
];

// ─── Client bookings (made by clientUsers) ─────────────────────────────────
const clientBookings = [
  {
    id: uuidv4(),
    clientUserId: clientUsers[0].id,
    establishmentId: defaultRestaurantId,
    establishmentName: "The Grand Bistro",
    establishmentType: "restaurant",
    date: "2026-06-10",
    time: "19:30",
    partySize: 2,
    status: "confirmed",
    specialRequests: "Anniversary dinner, window table please",
    createdAt: new Date("2026-06-01").toISOString(),
  },
  {
    id: uuidv4(),
    clientUserId: clientUsers[0].id,
    establishmentId: est3Id,
    establishmentName: "Grand Legacy Hotel",
    establishmentType: "hotel",
    date: "2026-05-20",
    time: "20:00",
    partySize: 4,
    status: "completed",
    specialRequests: "",
    createdAt: new Date("2026-05-15").toISOString(),
  },
  {
    id: uuidv4(),
    clientUserId: clientUsers[0].id,
    establishmentId: est2Id,
    establishmentName: "Oasis Lounge & Bar",
    establishmentType: "bar",
    date: "2026-04-14",
    time: "21:00",
    partySize: 3,
    status: "completed",
    specialRequests: "",
    createdAt: new Date("2026-04-10").toISOString(),
  },
];

// ─── Ratings ───────────────────────────────────────────────────────────────
const ratings = [
  {
    id: uuidv4(),
    clientUserId: clientUsers[0].id,
    establishmentId: est3Id,
    score: 5,
    comment: "Absolutely stunning hotel. The food and service were impeccable.",
    createdAt: new Date("2026-05-21").toISOString(),
  },
  {
    id: uuidv4(),
    clientUserId: clientUsers[0].id,
    establishmentId: est2Id,
    score: 4,
    comment:
      "Great vibe and amazing cocktails. A bit loud but totally expected.",
    createdAt: new Date("2026-04-15").toISOString(),
  },
  {
    id: uuidv4(),
    clientUserId: clientUsers[1].id,
    establishmentId: defaultRestaurantId,
    score: 5,
    comment: "Best bistro in the city. The truffle risotto is a must-try.",
    createdAt: new Date("2026-03-10").toISOString(),
  },
];

// ─── Settings ──────────────────────────────────────────────────────────────
const settingsByRestaurant = {
  [defaultRestaurantId]: {
    ...createDefaultSettings("The Grand Bistro"),
    address: "24 Rue de la Paix, Paris 75001",
    phone: "+33 1 42 96 00 00",
    email: "contact@grandbistro.com",
  },
};

const getRestaurantSettings = (restaurantId, restaurantName) => {
  if (!settingsByRestaurant[restaurantId]) {
    settingsByRestaurant[restaurantId] = createDefaultSettings(restaurantName);
  }
  return settingsByRestaurant[restaurantId];
};

module.exports = {
  users,
  clientUsers,
  clients,
  menuItems,
  reservations,
  clientBookings,
  ratings,
  establishments,
  settingsByRestaurant,
  createDefaultSettings,
  getRestaurantSettings,
};
